version: '3.8'

services:
  api:
    image: planckapi:0.1
    build:
      context: ./api
      dockerfile: ../docker/api.dockerfile
    restart: on-failure
    volumes:
    - ./api:/home/user/app/api
    - ./api/static:/home/user/app/api/static
    - ./api/media:/home/user/app/api/media
    ports:
    - "8000:8000"
    links:
      - db
    depends_on:
      - worker

  db:
    image: postgis/postgis
    restart: on-failure
    volumes:
      - ./docker/db/:/var/lib/postgresql/data
    ports:
    - 5432:5432
    environment:
      - POSTGRES_USER=planck
      - POSTGRES_PASSWORD=planck@123
      - POSTGRES_DB=planck

  redis:
    image: redis:alpine
    ports:
    - 6379:6379

  worker:
    build:
      context: ./api
      dockerfile: ../docker/api.dockerfile
    command: celery -A PlanckAPI worker -l debug --workdir /home/user/app/api
    volumes:
      - ./api:/home/user/app/api
      - ./api/static:/home/user/app/api/static
      - ./api/media:/home/user/app/api/media
    depends_on:
      - redis
      - db

  web:
    build:
      context: ./web
      dockerfile: ../docker/web.dockerfile
    volumes:
      - ./web/:/app
      - /app/node_modules
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
    command: "npm start"
    depends_on:
      - api
    stdin_open: true